FROM nginx
ENV AUTHOR=Docker

WORKDIR /HOME/VSTS/WORK/1/**/Dockerfile/nginx/html
COPY Hello_docker.html /usr/share/nginx/html

CMD cd /HOME/VSTS/WORK/1/**/Dockerfilenginx/html && sed -e s/Docker/"$AUTHOR"/ Hello_docker.html > index.html ; nginx -g 'daemon off;'
