version: '3.3'

services:
  web:
    image: DevTest89/mine
    ports:
     - "80:80"

  words:
    image: DevTest89/mine-api
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M

  db:
    image: DevTest89/mine-db